name: Build Manic Miner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up SDL2
      run: sudo apt-get install libsdl2-dev

    - name: Build Manic Miner
      run: |
        make dir
        make all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: manicminer
        path: manicminer
